# Generated by Django 6.0.5 on 2026-05-17 09:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=150)),
                ('degree', models.CharField(max_length=100)),
                ('field_of_study', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Honors, activities, or key modules')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education History',
                'verbose_name_plural': 'Education History',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if currently working here', null=True)),
                ('current', models.BooleanField(default=False, help_text='Is this your current role?')),
                ('description', models.TextField(help_text='Detail your key accomplishments and responsibilities (bullet points recommended)')),
                ('order', models.IntegerField(default=0, help_text='Sorting order (lower numbers display first)')),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your full name', max_length=100)),
                ('title', models.CharField(help_text='Professional title (e.g. Lead Full-Stack Architect)', max_length=150)),
                ('hero_title', models.CharField(blank=True, help_text='Main headline on Hero section', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Supporting sub-headline on Hero section')),
                ('bio_short', models.TextField(help_text='A short, catchy one-paragraph bio')),
                ('bio_detailed', models.TextField(blank=True, help_text='Detailed about me story')),
                ('profile_image', models.ImageField(blank=True, help_text='Your professional portrait', null=True, upload_to='profile/')),
                ('about_image', models.ImageField(blank=True, help_text='Secondary image for about section', null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, help_text='PDF Resume download', null=True, upload_to='resume/')),
                ('email', models.EmailField(help_text='Primary professional email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional contact number', max_length=20)),
                ('location', models.CharField(help_text='City, Country', max_length=100)),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('behance_url', models.URLField(blank=True, help_text='Behance/Dribbble profile URL')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Title Tag (e.g. Raviranjan | Creative Portfolio)', max_length=80)),
                ('meta_description', models.CharField(blank=True, help_text='SEO Meta Description (150-160 chars)', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=255)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps / Cloud'), ('design', 'UI/UX Design'), ('other', 'Other Tools')], default='other', max_length=20)),
                ('icon_class', models.CharField(blank=True, help_text='Devicon/FontAwesome class name (e.g. devicon-python-plain)', max_length=100)),
                ('proficiency', models.IntegerField(default=80, help_text='Proficiency percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('featured', models.BooleanField(default=True, help_text='Show in featured skills section')),
                ('order', models.IntegerField(default=0, help_text='Custom display ordering')),
            ],
            options={
                'verbose_name': 'Technology / Skill',
                'verbose_name_plural': 'Technologies & Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_title', models.CharField(help_text='e.g. CTO, ACME Corp or Co-Founder', max_length=100)),
                ('quote', models.TextField(help_text='Testimonial text')),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('project_relation', models.CharField(blank=True, help_text='e.g. Built AgriPower System', max_length=150)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('short_description', models.CharField(help_text='Brief summary shown on portfolio cards', max_length=250)),
                ('description', models.TextField(help_text='Detailed markdown-compatible description of the project')),
                ('image', models.ImageField(help_text='Primary portfolio image (1200x800px recommended)', upload_to='projects/')),
                ('image_gallery', models.ImageField(blank=True, help_text='Secondary image for inside details', null=True, upload_to='projects/gallery/')),
                ('demo_url', models.URLField(blank=True, verbose_name='Live Demo URL')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Repository URL')),
                ('featured', models.BooleanField(default=False, help_text='Feature this project prominently on the homepage')),
                ('order', models.IntegerField(default=0, help_text='Sorting order (lower numbers display first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(help_text='Select tools/languages used', related_name='projects', to='portfolio.technology')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
